### ISSUE TITLE
Multiple of the same song in the queue causes reordering problems

### ISSUE THREAD

**Issue by gGliner** [gGliner/soundcloud-queue#17]

**Comment by evanpaul** [comment]
Fixed issue in master branch

**Comment by evanpaul** [comment]
Alright I lied, working on a new solution.

**Comment by jgliner** [comment]
Why in god's name are we still using jQuery? React is where it's at.

**Comment by gGliner** [comment]
Lol remake the whole thing in react if you want

On Fri, Mar 25, 2016 at 9:19 AM Jarrett Gliner

<
mailto:Jarrett Gliner notifications@github.com

> wrote:

Why in god's name are we still using jQuery? React is where it's at.

—

You are receiving this because you authored the thread.

Reply to this email directly or
https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gGliner_soundcloud-2Dqueue_issues_17-23issuecomment-2D201348474&d=CwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=mxGdBqxyMkJEewYPTbCScg&m=bod-aDz9XdvRQoldjYRuG5vZtP_yPowwFH1Cvgmou2U&s=6Wt43tZeyu4BhvBBFZxaoETOY2jiMDhtSCK9zx06zLA&e=
https://github.com/gGliner/soundcloud-queue/issues/17#issuecomment-201348474

**Comment by evanpaul** [comment]
Duplicates disabled for the time being
